-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 24-Jan-2017 às 21:35
-- Versão do servidor: 10.1.16-MariaDB
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lab_mvc_default`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `noticias`
--

CREATE TABLE `noticias` (
  `noticia_id` int(11) NOT NULL,
  `noticia_data` datetime DEFAULT '0000-00-00 00:00:00',
  `noticia_autor` varchar(255) DEFAULT NULL,
  `noticia_titulo` varchar(255) DEFAULT NULL,
  `noticia_texto` text,
  `noticia_imagem` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `noticias`
--

INSERT INTO `noticias` (`noticia_id`, `noticia_data`, `noticia_autor`, `noticia_titulo`, `noticia_texto`, `noticia_imagem`) VALUES
(6, '0000-00-00 00:00:00', 'adriano', 'Venezuelanos são obrigados a sobreviver com apenas $1 por dia', 'CARACAS, Venezuela – Os venezuelanos celebraram o Natal no rescaldo de violentos protestos e saques que ocorreram em algumas partes do país, em consequência da escassez de dinheiro.\r\n\r\nA decisão do governo de eliminar o maior projeto de lei antes da chegada de novas e maiores contas foi a mais recente de uma série de erros financeiros em uma crise financeira paralisante de três anos.\r\n\r\nO presidente Nicolás Maduro voltou atrás, dizendo aos venezuelanos que continuem usando as notas de 100 bolívares – que valem apenas 4 centavos americanos no mercado negro – até 2 de janeiro.', '_949622924.'),
(7, '0000-00-00 00:00:00', 'adriano', 'Colapso de mina de carvão na Índia deixa 15 soterrados', 'O colapso de uma mina de carvão na Índia deixou cinco trabalhadores mortos e cerca de 15 pessoas soterradas até o momento. De acordo com os primeiros registos do ocorrido.\r\n\r\nO desastre se sucedeu durante uma mudança de turno noturna na última quinta-feira, no distrito de Godda, estado de Jharkhands ao norte da Índia, conforme publicado na edição online do jornal Times of India.', '_857173346.'),
(8, '0000-00-00 00:00:00', 'adriano', 'WikiLeaks diz que e-mails de Hillary são de fonte democrata, não de russos', 'Um ex-embaixador britânico no Uzbequistão, que é próximo do fundador do WikiLeaks, Julian Assange, disse ao Daily Mail que a Rússia não divulgou e-mails da campanha de Hillary Clinton e funcionários democratas à organização anti-sigilo.\r\n\r\nCraig Murray, que se descreve agora como um funcionário do WikiLeaks, disse ao tablóide que ele voou para Washington, D.C. para receber arquivos de uma fonte, que ele descreveu como um delator do Partido Democrata. Ele disse que não haviam hackers envolvidos, como tem sido alegado pelas fontes da CIA em vários relatórios de novas mídias, bem como em um artigo do Washington Post, que alegou que os hackers apoiados pela Rússia influenciaram a eleição em favor de Donald Trump sobre Hillary Clinton.\r\n\r\n“Nenhum dos vazamentos veio dos russos”, disse Murray na terça-feira. “A fonte tinha acesso legal às informações. Os documentos vieram de vazamentos internos, não de hackers. ”', '_25685059.'),
(9, '0000-00-00 00:00:00', 'adriano', 'Parlamento da Coreia do Sul aprova impeachment da presidente', 'O parlamento da Coreia do Sul aprovou hoje (9) o impeachment da presidente Park Geun-hye, que foi acusada de envolvimento em um escândalo de tráfico de influência. Desta forma, ela está para se tornar a primeira líder eleita do país a ser afastada do cargo. Imediatamente após a aprovação do impeachment, os poderes de Park serão transferidos ao primeiro-ministro, Hwang Kyo-ahn, que está à espera da decisão do Tribunal Constitucional, o qual pode sancionar ou cancelar a sentença parlamentar.\r\n\r\nA decisão dos parlamentares pelo impedimento teve 234 votos favoráveis e 56 contrários, o que mostra que dezenas de membros do partido de Park, o conservador Saenuri, deram seu apoio ao processo. Para que o pedido fosse aprovado, havia a necessidade de um mínimo de 200 votos de um total de 300 assentos.', '_112283247.'),
(10, '0000-00-00 00:00:00', 'adriano', 'Venezuela é suspensa do Mercosul por descumprir normas do bloco', 'Venezuela foi notificada hoje (2) da suspensão de seus direitos como participante do Mercosul, por descumprir as normas praticadas pelo bloco. A adaptação do país às regras tinha como prazo a meia-noite de quinta-feira.\r\n\r\n“Constatada a persistência do descumprimento assumido no referido protocolo de adesão se notifica, mediante a presente comunicação à República Bolivariana da Venezuela, a cessação de exercício dos direitos inerentes à sua condição de Estado parte do Mercosul a partir desta data até que os Estados parte signatários do Tratado de Assunção acordem com a República Bolivariana da Venezuela as condições para restabelecer o exercício de seus direitos como Estado parte”, disse o comunicado.', '_1693163227.'),
(11, '0000-00-00 00:00:00', 'adriano', 'Trump e Obama respondem à morte de Fidel Castro', 'O presidente eleito Donald Trump e o presidente Barack Obama divulgaram declarações sobre a morte do ditador comunista cubano Fidel Castro, que morreu aos 90 anos no sábado (26).\r\n\r\nSuas respostas foram muito diferentes, fornecendo um dos exemplos mais pontuais das opiniões de Obama e Trump.\r\n\r\n“Fidel Castro está morto!”, Trump postou no sábado para seus milhões de seguidores no Twitter. Mais tarde, ele criticou severamente o regime de Castro. “O legado de Fidel Castro são os pelotões de fuzilamento, roubo, sofrimento inimaginável, pobreza e negação dos direitos humanos fundamentais”, disse Trump em um comunicado.', '_1965310030.'),
(12, '0000-00-00 00:00:00', 'adriano', 'Cubanos em Miami: celebração e reflexão após morte de Fidel Castro', 'MIAMI — Vestindo uma camiseta que dizia “Bahia dos Porcos”, Rafael Torre, 80, era um em meio a multidão de centenas de cubanos que celebraram a morte de Fidel Castro, o ex-ditador comunista de Cuba. Torre estava abismado com o fato de Castro ter mantido o poder por mais tempo do que qualquer outro líder nacional vivo, exceto a rainha Elizabeth II da Inglaterra.\r\n\r\nExilados cubanos, como Torre, tentaram inúmeras estratégias para remover Castro do poder depois que ele tomou o controle de Cuba em 1959. A fracassada invasão da CIA pela “Bahia dos Porcos” em 1961 foi uma dessas tentativas. Agora, como muitos outros, Torre está esperançoso com relação ao futuro da ilha já que o ex-líder cubano faleceu.', '_2027260690.'),
(13, '0000-00-00 00:00:00', 'adriano', 'Muro gigante é construído em Munique para isolar refugiados', 'Na semana em que se comemora 27 anos da queda do muro de Berlim, na Alemanha, um bloqueio de quatro metros de altura começou a ser construído em Munique.\r\n\r\nO muro, que provocou polêmica entre os moradores, tem cem metros de comprimento e seu objetivo é isolar um albergue para jovens refugiados.\r\n\r\nA obra começou por causa de uma briga judicial entre a administração de Munique e sete moradores de Neuperlach, um bairro de 55 mil habitantes localizado na região sudeste da cidade.\r\n\r\nCom capacidade para 160 menores, a instalação do albergue foi apresentada em 2014 e os moradores prestaram queixa sobre a provável “polução acústica” que seria provocada pelos jovens.', '_1006497645.'),
(14, '0000-00-00 00:00:00', 'adriano', '‘Não muda nada na relação Brasil e EUA’, diz presidente Temer', 'Através de sua conta oficial no Twitter, o presidente do Brasil, Michel Temer, comentou a vitória do republicano Donald Trump como presidente dos Estados Unidos. “Tenho certeza de que não muda nada na relação Brasil e EUA”, declarou Temer.\r\n\r\n“É claro que o novo presidente que assume terá de levar em conta as aspirações de todo o povo americano. Eu tenho dito que a relação do Brasil com os EUA e os demais países é institucional, ou seja, de Estado para Estado”, disse o presidente brasileiro.\r\n\r\nTrump é o 45º presidente eleito dos EUA. Ele derrotou a democrata Hillary Clinton na madrugada desta quarta-feira (9), aproximadamente às 5h, horário de Brasília. O número de delegados conquistados foi de pelo menos 278.', '_1880502932.'),
(15, '0000-00-00 00:00:00', 'adriano', 'Assembleia Nacional da Venezuela declara que país vive ditadura', 'Em sessão extraordinária realizada neste domingo (23), a Assembleia Nacional da Venezuela anunciou golpe de estado praticado por Nicolás Maduro ao impedir o processo de referendo revogatório, transformando o país, oficialmente, numa ditatura socialista.\r\n\r\nUma resolução foi aprovada pelos legisladores, que declara a “ruptura da ordem constitucional e a existência de um golpe de estado cometido pelo regime de Nicolás Maduro”, juntamente com a promessa de que haverá reação através de protestos em massa – com previsão para amanhã (26) – e pressão internacional. Horas antes, a Assembleia havia sido invadida por socialistas defensores do governo de Maduro na tentativa de impedir o andamento da sessão.\r\n\r\nOs simpatizantes do governo entraram de forma truculenta na sede da Assembleia Nacional, avançaram sobre a segurança e interromperam o debate, depois do qual se confirmou a violação da ordem constitucional e a existência de um golpe de Estado perpetrado pelo regime de Nicolás Maduro contra a Constituição.', '_1153822631.'),
(16, '0000-00-00 00:00:00', 'adriano', 'Primeira-ministra britânica quer dar início a Brexit em março', 'Em sua primeira reunião com líderes da União Europeia nesta quinta-feira (20), a primeira-ministra do Reino Unido, Theresa May, pretende expressar a irreversibilidade da decisão de retirada do país do bloco, o que se chamou de Brexit.\r\n\r\nA cúpula do Conselho Europeu deve durar dois dias, no transcorrer dos quais May fará uma breve declaração para os 27 países do bloco em meio ao jantar de que dará início aos procedimentos de saída, que calcula-se deve levar 2 anos, antes do fim de março.', '_79263755.'),
(17, '0000-00-00 00:00:00', 'adriano', 'França e Reino Unido iniciam obras de muro para barrar refugiados', 'França e Reino Unido começaram a construir uma polêmica muralha em Calais com o objetivo de bloquear o acesso de refugiados que decidem entrar no território britânico.\r\n\r\nA construção começou na semana passada e vai manter isolado o acampamento chamado de “Selva” dos túneis, barcos e veículos que conduzem ao Reino Unido.\r\n\r\nPor enquanto só o que se vê da “Grande Muralha de Calais” – como passou a ser chamada – é um canteiro de obras na beira da estrada, longe do centro da pequena cidade francesa.\r\n\r\nNo acampamento “Selva”, que já foi desfeito inúmeras vezes, estão alojados atualmente 7.000 migrantes. A cada vez em que é derrubado, os refugiados retornam e erguem de novo suas tendas.', '_1806139434.'),
(18, '0000-00-00 00:00:00', 'adriano', 'BitMEX: se operar com Bitcoin não for suficiente, experimente com alavancagem', 'Investidores chineses adoram especular em mercados extremamente voláteis. Eles efetivamente tomaram controle da moeda virtual Bitcoin, chegando a representar 90 por cento do volume de negociação global dessa moeda. E se operar na volátil criptomoeda Bitcoin não fosse o suficiente, com BitMEX estão tendo a oportunidade de usar uma alavancagem ainda maior.\r\n\r\n“Nosso objetivo é permitir qualquer um apostar em qualquer coisa a qualquer momento”, disse à Bloomberg o fundador da corretora BitMEX, Arthur Hayes. O ex-operador do Citigroup de 30 anos de idade fundou a BitMEX em Hong Kong há dois anos, modelando-o conforme as normas e os regulamentos da Bolsa de Mercadorias de Chicago (CME—Chicago Mercantile Exchange). O CME permite que especuladores comprem ou vendam grandes quantidades de commodities ou ativos financeiros colocando pouco dinheiro na operação.\r\n\r\nEste processo é chamado de especulação em margem, um processo que a BitMEX incorporou ao mundo da criptomoeda. Os operadores ou especuladores têm que depositar Bitcoin (ou outras criptomoedas) em vez de dólares, euros ou yuans para prover suas contas.\r\n\r\nEntão, eles podem usar 1 Bitcoin para comprar um contrato no valor de 100 Bitcoins—100 vezes é a alavancagem máxima permitida—e a BitMEX cobra uma taxa de 0,005 por cento para cada transação.', '_1311893630.'),
(19, '0000-00-00 00:00:00', 'adriano', 'Garry Kasparov, rei do xadrez, combate ditaduras em todo mundo', 'Garry Kasparov, muitas vezes considerado o maior jogador de xadrez de todos os tempos, vê a vida como uma batalha entre os opostos: bem e mal, ou liberdade e totalitarismo.\r\n\r\nAo se aposentar do xadrez profissional em 2005, Kasparov dedicou-se a uma guerra total com quem ele considera como pertencente às “forças do mal” — por exemplo, os regimes totalitários da China, Irã e Coreia do Norte —, que ameaçam as “forças do bem.”\r\n\r\nNa opinião de Kasparov, o maior inimigo do mundo livre é o líder russo Vladimir Putin, que é o assunto do seu livro de 2015, “O inverno está vindo”. Da perspectiva de Kasparov, não há meio termo: “se você não está do lado do bem, você deve, portanto, pertencer ao lado “sombrio da força”.\r\n\r\nEm 2011, Kasparov sucedeu Vaclav Havel (primeiro presidente da República Tcheca depois da separação Tcheca-Eslovaca) como presidente de uma Fundação de Direitos Humanos sediada em Nova York. A partir desse ponto, Kasparov focou sua energia para lutar pela liberdade e direitos humanos em todo mundo, trazendo para a batalha um sentido estratégico finamente alinhado com sua sabedoria de rei e campeão mundial de xadrez.', '_314415002.'),
(20, '0000-00-00 00:00:00', 'adriano', 'Mais de 100 pessoas fogem por dia da Venezuela para a Colômbia', 'Na tentativa de escapar da crise social, econômica e política que se abate sobre a Venezuela, mais de 100 pessoas entram todos os dias na cidade colombiana de Barranquilla. A informação foi divulgada por autoridades da Colômbia nesta segunda-feira (1º).\r\n\r\nColombianos que possuem filhos na Venezuela constituem a maior parte das famílias que entram na capital do Departamento (Estado) de Atlántico, de acordo com o procurador municipal de Barranquilla, Jaime Pugliese.\r\n\r\n“Desde o início de julho, em média, a cada dia são 25 núcleos familiares que se apresentam pela primeira vez à procuradoria para solicitar ajuda e assessoria”, destacou Pugliese. O funcionário informou também que sobretudo para suprir suas carências quanto à saúde é o que faz as pessoas se encaminharem para a entidade.', '_836062257.'),
(21, '0000-00-00 00:00:00', 'adriano', 'Governo venezuelano instaura campos de trabalho forçado', 'Em seu livro O Caminho da Servidão, F.A. Hayek explicou que, sob um governo socialista voltado para o planejamento centralizado da economia, o seguinte cenário irá ocorrer:\r\n\r\n1) Planos estatais serão criados com o intuito de impulsionar a economia.\r\n\r\n2) No entanto, por causa da impossibilidade prática de se fazer qualquer planejamento econômico sob um arranjo socialista, todos esses planos inevitavelmente irão fracassar.\r\n\r\n3) Ato contínuo, os planejadores econômicos irão responder criando ainda mais planos para “corrigir” os estragos gerados pelos planos anteriores. À medida que estes também inevitavelmente fracassam, os planejadores concedem a si próprios ainda mais poderes para “consertar a economia”, o que significa menos liberdade para os cidadãos e mais opressão do estado.\r\n\r\n4) Os planejadores econômicos, consequentemente, vão se tornando cada vez mais ditatoriais, e cada vez mais dispostos a jogar fora todo e qualquer resquício de moralidade. A população é continuamente escravizada, sendo levada para o caminho da servidão.', '_2122783749.'),
(22, '0000-00-00 00:00:00', 'adriano', 'Roubo de dados hospitalares será epidêmico em 2016, afirmam especialistas', 'Em cinco de fevereiro deste ano, hackers invadiram os computadores do Centro Médico Presbiteriano de Hollywood. Os arquivos foram confiscados e os hackers exigiram pagamento para desbloqueá-los.\r\n\r\nPara evitar perdas, o hospital pagou cerca de 17.000 dólares em bitcoin. Segundo a Associated Press, o CEO do hospital, Allen Stefanek, disse que o pagamento teve a intensão de “restaurar as operações ao normal”.\r\n\r\nO caso ganhou destaque nos EUA e o FBI está agora, supostamente, investigando a invasão.\r\n\r\nDe acordo com James Scott, co-fundador do Instituto de Tecnologia para Infraestruturas Críticas, no entanto, a violação pode ser apenas uma pequena amostra do que está por vir.', '_1668235605.'),
(23, '0000-00-00 00:00:00', 'adriano', 'Reino Unido terá segunda chefe de governo da sua história', 'Conforme divulgou o primeiro-ministro demissionário David Cameron, Theresa May assumirá a chefia do Governo do Reino Unido na próxima quarta-feira (13), como um dos efeitos da vitória do Brexit.\r\n\r\n“Teremos um novo primeiro-ministro neste edifício que está atrás de mim na quarta-feira”, falou Cameron em frente ao número 10 da Downing Street. Após a costumeira sessão de perguntas no Parlamento britânico, o ainda premiê entregará nas próximas horas a sua demissão à rainha Elizabeth II.\r\n\r\nPela segunda vez uma primeira-ministra assumirá o governo do Reino Unido. A primeira no cargo foi Margaret Thatcher, do Partido Conservador, que ficou conhecida como a “Dama de Ferro”.', '_988154967.'),
(24, '0000-00-00 00:00:00', 'adriano', 'Exclusivo: Hackers comprometem sistema bancário mundial', 'O sistema bancário global está sendo comprometido por cibercriminosos que têm demonstrado possuir alto nível de acesso, com controle quase total para alterar dados e roubar bancos, de acordo com o especialista Ed Alexander, que vem investigando-os no submundo da internet, a Darknet.\r\n\r\nEd Alexander é especialista em cyberHUMINT (inteligência humana na web) e expert em fóruns privados administrados por Hackers. Muitas vezes acessada apenas com um software especial, a darknet é usada por grupos criminosos para conspirar e vender mercadorias ilícitas.\r\n\r\nEm uma entrevista anterior, Alexander forneceu ao Epoch Times amplas evidências do atual assalto ao Banco Mundial. Anteriormente, decidiu que permaneceria anônimo, a fim de proteger suas investigações, mas agora veio a público com o objetivo de expor os dois grupos de hackers que estão por trás dos ataques.', '_363367793.'),
(25, '0000-00-00 00:00:00', 'adriano', 'Estado Islâmico divulga ‘lista da morte’ que inclui brasileiros', 'Na segunda-feira (6), o grupo terrorista Estado Islâmico anunciou os nomes de pessoas que seus membros em todo o mundo terão de matar. A “lista da morte” foi divulgada em suas redes de comunicação e contém os nomes de mais de oito mil pessoas, inclusive de brasileiros.\r\n\r\nA organização terrorista não anunciou precisamente quantos brasileiros foram “marcados para morrer”, mas calcula-se que a lista pode conter até 39 pessoas. A relação foi encontrada pelo grupo Vocativ, expert em investigações da conhecida “deep web”, a área da internet que não está acessível aos mecanismos de busca.\r\n\r\nNo total, a listagem ordena o assassinato de 8.318 pessoas do mundo todo, sendo a grande maioria de americanos. Os terroristas revelaram a relação em um grupo do aplicativo Telegram. Nela incluem-se nomes, endereços e emails dos alvos. A “lista da morte” foi tornada pública pela ramificação tecnológica do Estado Islâmico, o United Cyber Caliphate (Cyber-califado unificado, em tradução livre).', '_359027735.'),
(26, '0000-00-00 00:00:00', 'adriano', 'Capriles acusa Brasil de ‘indiferença’ diante da crise na Venezuela', 'Representando a oposição venezuelana, Henrique Capriles condenou a “indiferença” do Brasil com respeito à conjuntura política e econômica de seu país e solicitou que o governo Temer ajude na execução do referendo revogatório que poderá derrubar Nicolás Maduro. Capriles, que é governador do estado de Miranda e por duas vezes se candidatou a presidente, esteve no Paraguai e na Argentina antes de desembarcar no Brasil, onde se reuniu, na tarde nesta terça-feira (14), com o chanceler José Serra.\r\n\r\nAo sair de uma reunião com senadores que dão apoio à oposição na Venezuela, Capriles apelou ao País: “Está na hora, queremos que o governo do Brasil defenda os princípios constitucionais, da democracia. Espero que acabe a indiferença do Brasil, de coração.”', '_313624449.'),
(27, '0000-00-00 00:00:00', 'adriano', 'Após massiva espionagem chinesa, EUA expandem regras de segurança nacional', 'Ao longo de três semanas em abril, houve quatro casos de espionagem chinesa contra os EUA. Diante desta ameaça, os EUA expandiram suas regras para abertura de processo em casos que envolvam a segurança nacional.\r\n\r\nUma carta da procuradora-geral adjunta, Sally Q. Yates, teria supostamente circulado no meio de processos federais em março, de acordo com uma cópia alegadamente obtida pelo New York Times. A carta diz que “todos os casos que afetem a segurança nacional, até mesmos os irrelevantes, agora requerem coordenação e supervisão de Washington”.\r\n\r\nO New York Times publicou que “sempre houve intensão de se criar regras para esta situação, mas somente agora isto veio à tona”. A carta também pressupõe que “o termo ‘segurança nacional’ deveria ser considerado mais amplo”.\r\n\r\nO trecho não esclarece o que, de fato, foi mudado, no entanto uma olhada mais detalhada nas regras destes casos elucida um quadro bem mais claro.\r\n\r\nUm porta-voz do Department of Justice disse ao Epoch Times por e-mail que todas as mudanças nas regras estarão disponíveis no U.S. Attorneys’ Manual – o manual, de fato, exibe duas secções que foram atualizadas em março de 2016.\r\n\r\nQuando a nova versão do manual é comparada lado a lado com a versão anterior, de 14 de setembro de 2015, ela mostra que as definições para casos de segurança nacional foram expandidas.', '264808okamipng_370544486.png'),
(31, '0000-00-00 00:00:00', 'adriano', 'Mais hiper-realismo!', 'Tempão que a gente não fala de hiper-realismo por aqui (já falamos antes e você pode ver alguns posts igualmente de cair o queixo lá no final) né?\r\n\r\nBom aqui estamos nós com mais um dos mestres na arte do hiper-realismo. Há quem não veja grande vantagem nessas pinturas, porque pessoas estão fazendo o que câmeras fotográficas fazem. Mas temos que reconhecer o esforço FERRADO para parir uma obra dessas, né? Além do mais nem sempre o resultado são como fotos. Apesar de hiper-reais, algumas das obras podem ser vistas como pinturas muito bem realizadas.', '_1807857379.'),
(32, '0000-00-00 00:00:00', 'adriano', 'Pirógrafo solar: Pensa num trampo de paciência', 'Um Pirógrafo é uma ferramenta que tem uma ponta de níquel ou tungstênio que se aquece ao ponto de incandescer graças a uma resistência interna. Ele tem forma de caneta e com ele você pode ir queimando a madeira ou couro e assim vai fazendo o desenho que quiser com uma carbonização resultante da ponta quente no material.', '_49218223.'),
(33, '0000-00-00 00:00:00', 'adriano', 'Mundo Gump chega ao ano 11, completo 41 de idade e 18 de casamento', 'Num mesmo dia, para ficar mais fácil, eu faço aniversário, é a data de fundação deste blog, e é também meu aniversário de casamento numero 2. Não, eu não estou no segundo casamento, mas eu casei com a Nivea em dois dias diferentes, no civil dia 15 e no religioso dia 23 de janeiro.\r\n\r\nCaramba, como que pode? Eu já tenho 41 anos, amigos véios! É inacreditável isso porque minha mentalidade é de uns trinta e olhe lá! (confesso eventuais momentos de retardamento que são rebordosas dos 15, mas só de vez em quando)', '_1516774901.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `user` varchar(255) COLLATE utf8_bin NOT NULL,
  `user_password` varchar(255) COLLATE utf8_bin NOT NULL,
  `user_name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `user_session_id` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `user_permissions` longtext COLLATE utf8_bin
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Extraindo dados da tabela `users`
--

INSERT INTO `users` (`user_id`, `user`, `user_password`, `user_name`, `user_session_id`, `user_permissions`) VALUES
(2, 'guest', '$2a$08$PD.b2dsykLxcbiwsPWh6qu7p.rJEpRkPGfIHUxpfdnA1hfZeY4Ct6', 'guest', '5aac236f44eb14e8efd2f4ee7a5c6365', 'a:1:{i:0;s:13:"user-register";}'),
(3, 'teste', '$2a$08$82H18pYQrgputd40W59cqeIYz2ksSYX7CjyVoNj4u8UbToaFc4WqO', 'teste 2', 'ekttd27qevpod8ignmegib2gm5', 'a:1:{i:0;s:13:"user-register";}'),
(4, 'adriano', '$2a$08$CIEJahSf.TAxXU0tF1KVi.VwzOtHv37BElMbWN.RNdgm7cpcKoZMW', 'adriano', 'p8sr6l0umu9oeob7887puscpm2', 'a:2:{i:0;s:13:"user-register";i:1;s:18:"gerenciar-noticias";}');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`noticia_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `noticias`
--
ALTER TABLE `noticias`
  MODIFY `noticia_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
